"""Create stock tables with PostgreSQL

Revision ID: 64951d865498
Revises: 
Create Date: 2025-10-17 06:13:45.786283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64951d865498'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='証券コード'),
    sa.Column('company_name', sa.String(length=255), nullable=False, comment='企業名'),
    sa.Column('company_name_en', sa.String(length=255), nullable=True, comment='企業名（英語）'),
    sa.Column('market', sa.String(length=50), nullable=True, comment='市場名'),
    sa.Column('sector', sa.String(length=100), nullable=True, comment='業種'),
    sa.Column('industry', sa.String(length=100), nullable=True, comment='業界'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='アクティブフラグ'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新日時'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_info_id'), 'stock_info', ['id'], unique=False)
    op.create_index(op.f('ix_stock_info_symbol'), 'stock_info', ['symbol'], unique=True)
    op.create_table('stock_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='証券コード'),
    sa.Column('date', sa.DateTime(), nullable=False, comment='日付'),
    sa.Column('open_price', sa.Float(), nullable=True, comment='始値'),
    sa.Column('high_price', sa.Float(), nullable=True, comment='高値'),
    sa.Column('low_price', sa.Float(), nullable=True, comment='安値'),
    sa.Column('close_price', sa.Float(), nullable=True, comment='終値'),
    sa.Column('volume', sa.Integer(), nullable=True, comment='出来高'),
    sa.Column('adjusted_close', sa.Float(), nullable=True, comment='調整後終値'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='作成日時'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_prices_date'), 'stock_prices', ['date'], unique=False)
    op.create_index(op.f('ix_stock_prices_id'), 'stock_prices', ['id'], unique=False)
    op.create_index(op.f('ix_stock_prices_symbol'), 'stock_prices', ['symbol'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stock_prices_symbol'), table_name='stock_prices')
    op.drop_index(op.f('ix_stock_prices_id'), table_name='stock_prices')
    op.drop_index(op.f('ix_stock_prices_date'), table_name='stock_prices')
    op.drop_table('stock_prices')
    op.drop_index(op.f('ix_stock_info_symbol'), table_name='stock_info')
    op.drop_index(op.f('ix_stock_info_id'), table_name='stock_info')
    op.drop_table('stock_info')
    # ### end Alembic commands ###
